chat/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("chat/<str:room_name>/", views.room, name="room"),
    path('delete_room/<str:room_name>/', views.delete_room, name='delete_room'),
    path('signup/', views.register, name='signup'),
    path('profile/', views.profile, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from chat import views

router = routers.DefaultRouter()
router.register(r'rooms', views.RoomViewSet)

urlpatterns = [
    path("", include("chat.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += router.urls

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
import uuid


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='defaultavatar.png', upload_to='avatars', null=True, blank=True)
    user_uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    def __str__(self):
        return f'{self.user.username} Account'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.avatar:
            try:
                img = Image.open(self.avatar.path)
                max_size = (300, 300)
                if img.height > max_size[1] or img.width > max_size[0]:
                    img.thumbnail(max_size)
                    img.save(self.avatar.path)
                    
            except:
                self.avatar = 'defaultavatar.png'
                self.save(update_fields=['avatar'])


class Room(models.Model):
    room_name = models.CharField(max_length=128, unique=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.room_name


class Message(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField(max_length=280)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.room} - {self.user}'

chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Account


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']


class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['avatar']

chat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from rest_framework import viewsets, permissions

from .forms import SignUpForm, UserUpdateForm, AccountUpdateForm
from .models import Room, Message
from .serializers import RoomSerializer


class RoomViewSet(viewsets.ModelViewSet):
    queryset = Room.objects.all()
    serializer_class = RoomSerializer
    permission_classes = [permissions.IsAdminUser]


@login_required
def index(request):
    users = User.objects.exclude(pk=request.user.id)
    rooms = Room.objects.all()
    return render(request, 'index.html', {
        "users": users, 
        "rooms": rooms,
        })


@login_required
def room(request, room_name):
    room_object, created = Room.objects.get_or_create(room_name=room_name, defaults={'created_by': request.user})
    chats = Message.objects.filter(room=room_object) if not created else []
    return render(request, "room.html", {"room_name": room_name, 'chats': chats})


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required
def delete_room(request, room_name):
    room = get_object_or_404(Room, room_name=room_name)
    
    if request.user.is_superuser or room.created_by == request.user:
        room.delete()
        messages.success(request, f'Room {room_name} has been deleted.')
    else:
        messages.error(request, 'You do not have permission to delete this room.')

    return redirect('index')


@login_required
def profile(request):
    if request.method == 'POST':
        user_update_form = UserUpdateForm(request.POST, instance=request.user)
        account_update_form = AccountUpdateForm(request.POST, request.FILES, instance=request.user.account)
        if user_update_form.is_valid() and account_update_form.is_valid():
            user_update_form.save()
            account_update_form.save()
            messages.success(request, 'Your profile has been updated')
            return redirect('profile')
    else:
        user_update_form = UserUpdateForm(instance=request.user)
        account_update_form = AccountUpdateForm(instance=request.user.account)

    return render(request, 'profile.html', {
        'user_update_form': user_update_form,
        'account_update_form': account_update_form
    })

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Chat App</title>
    {% load static %}
    <link href="{% static 'style.css' %}" rel="stylesheet" />
</head>
<body image="">
    <nav class="nav-menu">
        <ul class="nav-ul">
            <li class="nav-li">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-li profile-li">
                <a class="nav-link" id="username" href="{% url 'profile' %}"> My Profile </a>
                <img class="avatar" src="{{ user.account.avatar.url }}" alt="Profile Picture">
            </li>
            {% if user.is_superuser %}
            <li class="nav-li">
                <a class="nav-link" href="{% url 'room-list' %}">Api</a>
            </li>
            {% endif %}
            <li>
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button class="nav-button" type="submit" style="font-size: 13px; padding-bottom: 34px;">Logout</button>
                </form>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% block content %}{% endblock content %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}
Chat App - Choose Room
{% endblock title %}
{% load static %}
{% block content %}
    <div class="container">
        <input class="textInput" id="room-name-input" type="text" placeholder="Create a new room"
        pattern="[\/^\/]" title="Character / and \ are not allowed">
        <p class="small-hint">*Characters / and \ are not allowed</p>
        <input class="button" id="room-name-submit" type="hidden" value="Enter">
    </div>
    <div class="users">
        <h3 class="users-p" style="text-decoration: underline;">Registered users</h3><p class="users-p">Click the name to send a message!</p>
        <div class="users-below">
            {% for user in users %}
                <ul class="users-ul">
                    <li class="users-li"><a href="/chat/{{ user.account.user_uuid }}" class="users-link" style="color: #fa4753">{{ user.username }}</a></li>
                </ul>
            {% endfor %}
        </div>
    </div>
    <div class="users">
        <h3 class="users-p" style="text-decoration: underline;">Join a Room</h3>
        <div class="users-below">
            {% for room in rooms %}
                <ul class="users-ul">
                    <li class="users-li">
                        <a href="/chat/{{ room.room_name }}" class="users-link" style="color: #fa4753">{{ room.room_name }}</a>
                        {% if user.is_superuser or room.created_by == user %}
                            <form action="{% url 'delete_room' room.room_name %}" method="post" style="display:inline;">
                                {% csrf_token %}
                                <button type="submit" class="delete-button">Delete</button>
                            </form>
                        {% endif %}
                    </li>
                </ul>
            {% endfor %}
        </div>
    </div>
    <script src="{% static 'index.js' %}"></script>
{% endblock content %}

templates/profile.html
{% extends 'base.html' %}
{% block title %} Chat App - Account {% endblock title %}
{% load static %}
{% block content %}
<div class="container">
    <img class="circle" src="{{ user.account.avatar.url }}" />
    <div class="media-body">
        <h2 class="user-h2">{{ user.username }}</h2>
    </div>
    <form method="POST" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="legend" style="font-size: smaller; color: #fa4753">Update your profile here</legend>
            {{ user_update_form }}
            {{ account_update_form }}
        </fieldset>
        <div class="button-container">
            <button type="submit" class="chat-button">Update</button>
            <a href="{% url 'index' %}" class="leaveButton">Back</a>       
        </div>
    </form>
</div>
<script>
    document.getElementById("avatar-clear_id").remove();
    document.querySelector("label[for='avatar-clear_id']").remove();
    document.querySelector("label[for='id_avatar']").remove();
</script>
{% endblock content %}

templates/room.html
{% extends 'base.html' %}
{% block title %}
Chat App - Chat Room
{% endblock title %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="room-title">
            <h3 class="title">Room: <a style="border: 1px; border-style: solid; border-radius: 5px; background-color: white; padding: 5px; color: #212121">{{ room_name }}</a></h3>
            <a class="leaveButton" href="{% url 'index' %}" style="float: right;">Leave Room</a>
        </div>
        <div id="chat-log">
            {% for chat in chats.all %}
                {% if chat.user.id == request.user.id %}
                    <div class="message sender" style="color:white;">
                        {{ chat.user.username }}: {{ chat.message }}
                    </div>
                {% else %}
                    <div class="message receiver" style="color: aquamarine;">
                        {{ chat.user.username }}: {{ chat.message }}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="chat-input-container">
            <input class="chat-text-input" id="chat-message-input" type="text" size="100" placeholder="Type your message here"><br><br>
            <input class="chat-button" id="chat-message-submit" type="button" value="Send">
        </div>
    </div>
    {{ room_name|json_script:"room_name" }}
    {{ request.user.id|json_script:"user_id" }}
    {{ request.user.username|json_script:"user_name" }}
    <script src="{% static 'room.js' %}"></script>
{% endblock content %}